name: Hello World
author: Sri
description: some description
inputs: 
  who-to-greet: 
    description: 'who to greet'
    required: true
    default: Sri
outputs:
  time:
    description: "The Greeting time"

runs: 
  using: 'docker'
  image: 'Dockerfile'
  # entrypoint:
  args:
    -  ${{ inputs.who-to-greet }}
    