name: CI
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]  

jobs:
  build:
   runs-on: ubuntu-latest
   env:
     SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
     SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}     
   steps:
     - uses: actions/checkout@v2   
     - name: Cache node_modules
       uses: actions/cache@v2
       with: 
         path: ~/.npm 
         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
           ${{ runner.os }}-node-
     - name: Use NodeJS
       uses: actions/setup-node@v1
       with:
         node-version: "12.x"
     - run: npm ci
#     - run: npm run format:check
     - run: npm test -- --coverage
       env:
         CI: true
     - name: Upload test coverage
       uses: actions/upload-artifact@v2
       with:
         name: code-coverage
         path: coverage    
     - run: npm install -g surge
     - name: Build project
       if: github.event_name == 'push' #&& startsWith(github.ref, 'refs/tags')
       run: npm run build  
     - name: Upload build Folder
       uses: actions/upload-artifact@v2 #psu
       if: github.event_name == 'push'
       with:
         name: build
         path: build
     - name: Zip assets 
       if: github.event_name == 'push' && github.ref == 'refs/heads/master'
       run: |
         zip -r build.zip ./build 
         zip -r coverage.zip ./coverage  
     - name: Create a Release
       if: github.event_name == 'push' && github.ref == 'refs/heads/master'
       run: npx semantic-release
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - name: Deploy to staging
       if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
       run: npx surge --project ./build --domain superb-hope.surge.sh
     - name: Deploy to production
       if: github.event_name == 'push' && github.ref == 'refs/heads/master'
       run: npx surge --project ./build --domain daily-board.surge.sh
     - name: Upload Code Coverage Reports
       if: github.event_name == 'push' && github.ref == 'refs/heads/master'
       run: npx codecov
       env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


       

